-- Contains data from the TG API
DROP TABLE IF EXISTS tg_transactions;

CREATE TABLE IF NOT EXISTS tg_transactions (
  id INT PRIMARY KEY,
  tax_key VARCHAR(13),
  tmk VARCHAR(18),
  rec_date DATE,
  doc_type VARCHAR(100),
  first_party_name VARCHAR(255),
  second_party_name VARCHAR(255),
  conveyance_amount INT,
  consideration_amount INT,
  condo_name VARCHAR(255),
  tax_class VARCHAR(50),
  transaction_type VARCHAR(50),
  neighborhood VARCHAR(100),
  region VARCHAR(100),
  owner_name VARCHAR(255),
  lessee VARCHAR(255),
  mailing_address VARCHAR(255),
  mailing_apartment_no VARCHAR(50),
  mailing_city VARCHAR(100),
  mailing_state VARCHAR(50),
  mailing_zip_code VARCHAR(20),
  mailing_country VARCHAR(100),
  total_market_value INT,
  building_market_value INT,
  land_market_value INT,
  building_value INT,
  land_value INT,
  total_assessed_value INT,
  building_exemption INT,
  land_exemption INT,
  total_exemption INT,
  net_value INT,
  total_net_value INT,
  current_total_market_value INT,
  current_building_market_value INT,
  current_land_market_value INT,
  current_building_value INT,
  current_land_value INT,
  current_total_assessed_value INT,
  current_building_exemption INT,
  current_land_exemption INT,
  current_total_exemption INT,
  current_net_value INT,
  current_total_net_value INT,
  property_address VARCHAR(255),
  zoning VARCHAR(50),
  property_area VARCHAR(50),
  mortgage_type VARCHAR(100),
  maturity_date DATE,
  INDEX idx_tax_key (tax_key),
  INDEX idx_tmk (tmk),
  INDEX idx_rec_date (rec_date),
  INDEX idx_neighborhood (neighborhood)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Title Guaranty API Data';