language: ruby
services:
  - mysql
  - redis-server

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

bundler_args: --without production

before_script:
  - mysql -u root -e 'create database uhero_db_test;'