UPDATE geographies SET display_name = 'ʻĀina Haina, Kuliʻouʻou', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96821';
UPDATE geographies SET display_name = 'Ala Moana, Ward, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96814';
UPDATE geographies SET display_name = 'Anahola', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96703';
UPDATE geographies SET display_name = 'Captain Cook', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96704';
UPDATE geographies SET display_name = 'Discovery Harbour', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96772';
UPDATE geographies SET display_name = 'Downtown Honolulu, Pauoa, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96813';
UPDATE geographies SET display_name = 'ʻEwa Gentry', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96706';
UPDATE geographies SET display_name = 'Haʻikū-Paʻuwela', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96708';
UPDATE geographies SET display_name = 'Hanapēpē', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96716';
UPDATE geographies SET display_name = 'Hauʻula', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96717';
UPDATE geographies SET display_name = 'Hawaiʻi Kai', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96825';
UPDATE geographies SET display_name = 'Hawaiian Acres', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96760';
UPDATE geographies SET display_name = 'Hawaiian Beaches', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96778';
UPDATE geographies SET display_name = 'Hawaiian Ocean View', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96737';
UPDATE geographies SET display_name = 'Hawaiian Paradise Park', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96749';
UPDATE geographies SET display_name = 'Hilo', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96720';
UPDATE geographies SET display_name = 'Honalo', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96725';
UPDATE geographies SET display_name = 'Honokaʻa', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96727';
UPDATE geographies SET display_name = 'Hāwī', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96719';
UPDATE geographies SET display_name = 'Kāhala, Kaimukī, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96816';
UPDATE geographies SET display_name = 'Kahuku', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96731';
UPDATE geographies SET display_name = 'Kahului', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96732';
UPDATE geographies SET display_name = 'Kailua', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96734';
UPDATE geographies SET display_name = 'Kailua-Kona', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96740';
UPDATE geographies SET display_name = 'Kalihi, Moanalua, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96819';
UPDATE geographies SET display_name = 'Kalāheo', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96741';
UPDATE geographies SET display_name = 'Kāneʻohe', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96744';
UPDATE geographies SET display_name = 'Kapaʻa', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96746';
UPDATE geographies SET display_name = 'Kapaʻau', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96755';
UPDATE geographies SET display_name = 'Kaunakakai', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96748';
UPDATE geographies SET display_name = 'Kealakekua', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96750';
UPDATE geographies SET display_name = 'Kekaha', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96752';
UPDATE geographies SET display_name = 'Kīhei', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96753';
UPDATE geographies SET display_name = 'Kīlauea', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96754';
UPDATE geographies SET display_name = 'Kōloa', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96756';
UPDATE geographies SET display_name = 'Kula', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96790';
UPDATE geographies SET display_name = 'Lāhainā', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96761';
UPDATE geographies SET display_name = 'Lāʻie', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96762';
UPDATE geographies SET display_name = 'Lānaʻi City', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96763';
UPDATE geographies SET display_name = 'Līhuʻe', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96766';
UPDATE geographies SET display_name = 'Makakilo', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96707';
UPDATE geographies SET display_name = 'Makiki, Mānoa, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96822';
UPDATE geographies SET display_name = 'McCully, Mōʻiliʻili, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96826';
UPDATE geographies SET display_name = 'Mililani', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96789';
UPDATE geographies SET display_name = 'Mountain View', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96771';
UPDATE geographies SET display_name = 'Nuʻuanu, Liliha, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96817';
UPDATE geographies SET display_name = 'Pāʻia', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96779';
UPDATE geographies SET display_name = 'Pearl City', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96782';
UPDATE geographies SET display_name = 'Princeville', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96722';
UPDATE geographies SET display_name = 'Pukalani', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96768';
UPDATE geographies SET display_name = 'Pūpūkea', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96712';
UPDATE geographies SET display_name = 'Salt Lake, JBPHH, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96818';
UPDATE geographies SET display_name = 'Volcano', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96785';
UPDATE geographies SET display_name = 'Wahiawā', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96786';
UPDATE geographies SET display_name = 'Waialua', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96791';
UPDATE geographies SET display_name = 'Waikīkī, Kapahulu, etc.', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96815';
UPDATE geographies SET display_name = 'Waikōloa Village', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96738';
UPDATE geographies SET display_name = 'Wailuku', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96793';
UPDATE geographies SET display_name = 'Waimalu', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96701';
UPDATE geographies SET display_name = 'Waimea', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96743';
UPDATE geographies SET display_name = 'Waimānalo', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96795';
UPDATE geographies SET display_name = 'Waipahu', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96797';
UPDATE geographies SET display_name = 'Waiānae', updated_at = NOW() WHERE universe = 'HHF' AND handle = '96792';
