require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExportsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Export. As you add validations to Export, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    xit "assigns all exports as @exports" do
      export = Export.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:exports)).to eq([export])
    end
  end

  describe "GET #show" do
    xit "assigns the requested export as @export" do
      export = Export.create! valid_attributes
      get :show, params: {id: export.to_param}, session: valid_session
      expect(assigns(:export)).to eq(export)
    end
  end

  describe "GET #new" do
    xit "assigns a new export as @export" do
      get :new, params: {}, session: valid_session
      expect(assigns(:export)).to be_a_new(Export)
    end
  end

  describe "GET #edit" do
    it "assigns the requested export as @export" do
      export = Export.create! valid_attributes
      get :edit, params: {id: export.to_param}, session: valid_session
      expect(assigns(:export)).to eq(export)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      xit "creates a new Export" do
        expect {
          post :create, params: {export: valid_attributes}, session: valid_session
        }.to change(Export, :count).by(1)
      end

      xit "assigns a newly created export as @export" do
        post :create, params: {export: valid_attributes}, session: valid_session
        expect(assigns(:export)).to be_a(Export)
        expect(assigns(:export)).to be_persisted
      end

      xit "redirects to the created export" do
        post :create, params: {export: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Export.last)
      end
    end

    context "with invalid params" do
      xit "assigns a newly created but unsaved export as @export" do
        post :create, params: {export: invalid_attributes}, session: valid_session
        expect(assigns(:export)).to be_a_new(Export)
      end

      xit "re-renders the 'new' template" do
        post :create, params: {export: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      xit "updates the requested export" do
        export = Export.create! valid_attributes
        put :update, params: {id: export.to_param, export: new_attributes}, session: valid_session
        export.reload
        skip("Add assertions for updated state")
      end

      xit "assigns the requested export as @export" do
        export = Export.create! valid_attributes
        put :update, params: {id: export.to_param, export: valid_attributes}, session: valid_session
        expect(assigns(:export)).to eq(export)
      end

      xit "redirects to the export" do
        export = Export.create! valid_attributes
        put :update, params: {id: export.to_param, export: valid_attributes}, session: valid_session
        expect(response).to redirect_to(export)
      end
    end

    context "with invalid params" do
      xit "assigns the export as @export" do
        export = Export.create! valid_attributes
        put :update, params: {id: export.to_param, export: invalid_attributes}, session: valid_session
        expect(assigns(:export)).to eq(export)
      end

      xit "re-renders the 'edit' template" do
        export = Export.create! valid_attributes
        put :update, params: {id: export.to_param, export: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    xit "destroys the requested export" do
      export = Export.create! valid_attributes
      expect {
        delete :destroy, params: {id: export.to_param}, session: valid_session
      }.to change(Export, :count).by(-1)
    end

    xit "redirects to the exports list" do
      export = Export.create! valid_attributes
      delete :destroy, params: {id: export.to_param}, session: valid_session
      expect(response).to redirect_to(exports_url)
    end
  end

end
