require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FeatureTogglesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FeatureToggle. As you add validations to FeatureToggle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeatureTogglesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before(:each) do
    @request.env['devise.mapping'] = Devise.mappings[:user]
    user = FactoryGirl.create(:user)
    sign_in user
  end

  describe "GET #index" do
    it "assigns all feature_toggles as @feature_toggles" do
      feature_toggle = FeatureToggle.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:feature_toggles)).to eq([feature_toggle])
    end
  end

  describe "GET #show" do
    it "assigns the requested feature_toggle as @feature_toggle" do
      feature_toggle = FeatureToggle.create! valid_attributes
      get :show, params: {id: feature_toggle.to_param}, session: valid_session
      expect(assigns(:feature_toggle)).to eq(feature_toggle)
    end
  end

  describe "GET #new" do
    it "assigns a new feature_toggle as @feature_toggle" do
      get :new, params: {}, session: valid_session
      expect(assigns(:feature_toggle)).to be_a_new(FeatureToggle)
    end
  end

  describe "GET #edit" do
    it "assigns the requested feature_toggle as @feature_toggle" do
      feature_toggle = FeatureToggle.create! valid_attributes
      get :edit, params: {id: feature_toggle.to_param}, session: valid_session
      expect(assigns(:feature_toggle)).to eq(feature_toggle)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FeatureToggle" do
        expect {
          post :create, params: {feature_toggle: valid_attributes}, session: valid_session
        }.to change(FeatureToggle, :count).by(1)
      end

      it "assigns a newly created feature_toggle as @feature_toggle" do
        post :create, params: {feature_toggle: valid_attributes}, session: valid_session
        expect(assigns(:feature_toggle)).to be_a(FeatureToggle)
        expect(assigns(:feature_toggle)).to be_persisted
      end

      it "redirects to the created feature_toggle" do
        post :create, params: {feature_toggle: valid_attributes}, session: valid_session
        expect(response).to redirect_to(FeatureToggle.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved feature_toggle as @feature_toggle" do
        post :create, params: {feature_toggle: invalid_attributes}, session: valid_session
        expect(assigns(:feature_toggle)).to be_a_new(FeatureToggle)
      end

      it "re-renders the 'new' template" do
        post :create, params: {feature_toggle: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested feature_toggle" do
        feature_toggle = FeatureToggle.create! valid_attributes
        put :update, params: {id: feature_toggle.to_param, feature_toggle: new_attributes}, session: valid_session
        feature_toggle.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested feature_toggle as @feature_toggle" do
        feature_toggle = FeatureToggle.create! valid_attributes
        put :update, params: {id: feature_toggle.to_param, feature_toggle: valid_attributes}, session: valid_session
        expect(assigns(:feature_toggle)).to eq(feature_toggle)
      end

      it "redirects to the feature_toggle" do
        feature_toggle = FeatureToggle.create! valid_attributes
        put :update, params: {id: feature_toggle.to_param, feature_toggle: valid_attributes}, session: valid_session
        expect(response).to redirect_to(feature_toggle)
      end
    end

    context "with invalid params" do
      it "assigns the feature_toggle as @feature_toggle" do
        feature_toggle = FeatureToggle.create! valid_attributes
        put :update, params: {id: feature_toggle.to_param, feature_toggle: invalid_attributes}, session: valid_session
        expect(assigns(:feature_toggle)).to eq(feature_toggle)
      end

      it "re-renders the 'edit' template" do
        feature_toggle = FeatureToggle.create! valid_attributes
        put :update, params: {id: feature_toggle.to_param, feature_toggle: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested feature_toggle" do
      feature_toggle = FeatureToggle.create! valid_attributes
      expect {
        delete :destroy, params: {id: feature_toggle.to_param}, session: valid_session
      }.to change(FeatureToggle, :count).by(-1)
    end

    it "redirects to the feature_toggles list" do
      feature_toggle = FeatureToggle.create! valid_attributes
      delete :destroy, params: {id: feature_toggle.to_param}, session: valid_session
      expect(response).to redirect_to(feature_toggles_url)
    end
  end

end
