require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TsdFilesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # TsdFile. As you add validations to TsdFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TsdFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before(:each) do
    @request.env['devise.mapping'] = Devise.mappings[:user]
    user = FactoryGirl.create(:user)
    sign_in user
  end

  describe "GET #index" do
    it "assigns all tsd_files as @tsd_files" do
      tsd_file = TsdFile.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:tsd_files)).to eq([tsd_file])
    end
  end

  describe "GET #show" do
    it "assigns the requested tsd_file as @tsd_file" do
      tsd_file = TsdFile.create! valid_attributes
      get :show, params: {id: tsd_file.to_param}, session: valid_session
      expect(assigns(:tsd_file)).to eq(tsd_file)
    end
  end

  describe "GET #new" do
    it "assigns a new tsd_file as @tsd_file" do
      forecast_snapshot = ForecastSnapshot.create! name: 'test', version: 'v1'
      get :new, {forecast_snapshot_id: forecast_snapshot.id}, session: valid_session
      expect(assigns(:tsd_file)).to be_a_new(TsdFile)
    end
  end

  describe "GET #edit" do
    it "assigns the requested tsd_file as @tsd_file" do
      tsd_file = TsdFile.create! valid_attributes
      get :edit, params: {id: tsd_file.to_param}, session: valid_session
      expect(assigns(:tsd_file)).to eq(tsd_file)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TsdFile" do
        expect {
          post :create, params: {tsd_file: valid_attributes}, session: valid_session
        }.to change(TsdFile, :count).by(1)
      end

      it "assigns a newly created tsd_file as @tsd_file" do
        post :create, params: {tsd_file: valid_attributes}, session: valid_session
        expect(assigns(:tsd_file)).to be_a(TsdFile)
        expect(assigns(:tsd_file)).to be_persisted
      end

      it "redirects to the created tsd_file" do
        post :create, params: {tsd_file: valid_attributes}, session: valid_session
        expect(response).to redirect_to(TsdFile.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved tsd_file as @tsd_file" do
        post :create, params: {tsd_file: invalid_attributes}, session: valid_session
        expect(assigns(:tsd_file)).to be_a_new(TsdFile)
      end

      it "re-renders the 'new' template" do
        post :create, params: {tsd_file: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tsd_file" do
        tsd_file = TsdFile.create! valid_attributes
        put :update, params: {id: tsd_file.to_param, tsd_file: new_attributes}, session: valid_session
        tsd_file.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tsd_file as @tsd_file" do
        tsd_file = TsdFile.create! valid_attributes
        put :update, params: {id: tsd_file.to_param, tsd_file: valid_attributes}, session: valid_session
        expect(assigns(:tsd_file)).to eq(tsd_file)
      end

      it "redirects to the tsd_file" do
        tsd_file = TsdFile.create! valid_attributes
        put :update, params: {id: tsd_file.to_param, tsd_file: valid_attributes}, session: valid_session
        expect(response).to redirect_to(tsd_file)
      end
    end

    context "with invalid params" do
      it "assigns the tsd_file as @tsd_file" do
        tsd_file = TsdFile.create! valid_attributes
        put :update, params: {id: tsd_file.to_param, tsd_file: invalid_attributes}, session: valid_session
        expect(assigns(:tsd_file)).to eq(tsd_file)
      end

      it "re-renders the 'edit' template" do
        tsd_file = TsdFile.create! valid_attributes
        put :update, params: {id: tsd_file.to_param, tsd_file: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested tsd_file" do
      tsd_file = TsdFile.create! valid_attributes
      expect {
        delete :destroy, params: {id: tsd_file.to_param}, session: valid_session
      }.to change(TsdFile, :count).by(-1)
    end

    it "redirects to the tsd_files list" do
      tsd_file = TsdFile.create! valid_attributes
      delete :destroy, params: {id: tsd_file.to_param}, session: valid_session
      expect(response).to redirect_to(tsd_files_url)
    end
  end

end
