-- HHF Universe Seed
-- Generated by seed.ts

-- Universe
INSERT IGNORE INTO universe (name) VALUES ('HHF');

-- Root category
INSERT INTO categories (universe, name, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'HHF', 0, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry IS NULL);
SET @root_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry IS NULL LIMIT 1);

-- Category: Access
INSERT INTO categories (universe, name, ancestry, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'access', @root_id, 0, 0, 0, 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'access');
SET @top_0_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'access' LIMIT 1);
SET @top_ancestry = CONCAT(@root_id, '/', @top_0_id);

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'amenities', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'amenities');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'amenities' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'amenities', @top_ancestry, 0, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'amenities');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'POICOUNT_GROCERY', 'poicount_grocery', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_GROCERY');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_GROCERY' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'POICOUNT_RECREATION', 'poicount_recreation', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_RECREATION');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_RECREATION' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'POICOUNT_RESTAURANTS_BARS', 'poicount_restaurants_bars', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_RESTAURANTS_BARS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_RESTAURANTS_BARS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'POICOUNT_HEALTH', 'poicount_health', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_HEALTH');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'POICOUNT_HEALTH' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'jobs', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'jobs');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'jobs' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'jobs', @top_ancestry, 1, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'jobs');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'JOBS_30', 'jobs_30', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_30');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_30' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'JOBS_D30', 'jobs_d30', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_D30');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_D30' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'JOBS_T30', 'jobs_t30', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_T30');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_T30' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'JOBS_D30_PERC', 'jobs_d30_perc', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_D30_PERC');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_D30_PERC' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'JOBS_T30_PERC', 'jobs_t30_perc', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_T30_PERC');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'JOBS_T30_PERC' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 4, 'indent0');

-- Category: Demographics
INSERT INTO categories (universe, name, ancestry, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'demographics', @root_id, 1, 0, 0, 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'demographics');
SET @top_1_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'demographics' LIMIT 1);
SET @top_ancestry = CONCAT(@root_id, '/', @top_1_id);

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'age-structure', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'age-structure');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'age-structure' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'age-structure', @top_ancestry, 0, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'age-structure');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE_85', 'age>85', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE_85');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE_85' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE7584', 'age7584', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE7584');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE7584' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE6574', 'age6574', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE6574');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE6574' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE5564', 'age5564', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE5564');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE5564' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE4554', 'age4554', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE4554');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE4554' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 4, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE3544', 'age3544', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE3544');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE3544' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 5, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE2534', 'age2534', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE2534');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE2534' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 6, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE1824', 'age1824', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE1824');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE1824' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 7, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE0517', 'age0517', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE0517');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE0517' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 8, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'AGE0004', 'age0004', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE0004');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'AGE0004' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 9, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'population', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'population');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'population' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'population', @top_ancestry, 1, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'population');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'POPULATION', 'population', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'POPULATION');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'POPULATION' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'racial-diversity', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'racial-diversity');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'racial-diversity' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'racial-diversity', @top_ancestry, 2, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'racial-diversity');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'ASIAN', 'asian', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'ASIAN');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'ASIAN' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'WHITE', 'white', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'WHITE');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'WHITE' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'BLACK', 'black', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'BLACK');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'BLACK' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'HAWPI', 'hawpi', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'HAWPI');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'HAWPI' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'household-income', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'household-income');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'household-income' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'household-income', @top_ancestry, 3, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'household-income');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDHHINC', 'medhhinc', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDHHINC');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDHHINC' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'unemployment', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'unemployment');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'unemployment' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'unemployment', @top_ancestry, 4, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'unemployment');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'UNEMPLOYMENT', 'unemployment', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'UNEMPLOYMENT');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'UNEMPLOYMENT' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'education', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'education');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'education' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'education', @top_ancestry, 5, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'education');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'COL', 'col', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'COL');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'COL' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'HS', 'hs', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'HS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'HS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');

-- Category: Housing Stock
INSERT INTO categories (universe, name, ancestry, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'housing-stock', @root_id, 2, 0, 0, 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'housing-stock');
SET @top_2_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'housing-stock' LIMIT 1);
SET @top_ancestry = CONCAT(@root_id, '/', @top_2_id);

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'housing-characteristics', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'housing-characteristics');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'housing-characteristics' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'housing-characteristics', @top_ancestry, 0, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'housing-characteristics');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'HOUSINGUNITS', 'housingunits', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'HOUSINGUNITS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'HOUSINGUNITS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDUNITAGE', 'medunitage', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDUNITAGE');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDUNITAGE' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'PERC_OWNER_NONLOCAL', 'perc_owner_nonlocal', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'PERC_OWNER_NONLOCAL');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'PERC_OWNER_NONLOCAL' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'new-project-permitted', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'new-project-permitted');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'new-project-permitted' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'new-project-permitted', @top_ancestry, 1, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'new-project-permitted');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEWSFR', 'newsfr', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWSFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWSFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEWMFR', 'newmfr', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWMFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWMFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEWSFR_5Y', 'newsfr_5y', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWSFR_5Y');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWSFR_5Y' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEWMFR_5Y', 'newmfr_5y', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWMFR_5Y');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEWMFR_5Y' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'permit-processing-time', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'permit-processing-time');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'permit-processing-time' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'permit-processing-time', @top_ancestry, 2, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'permit-processing-time');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDDELAYSFR', 'meddelaysfr', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYSFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYSFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDDELAYMFR', 'meddelaymfr', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYMFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYMFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDDELAYMFR_5Y', 'meddelaymfr_5y', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYMFR_5Y');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYMFR_5Y' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDDELAYSFR_5Y', 'meddelaysfr_5y', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYSFR_5Y');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDDELAYSFR_5Y' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'vacation-rentals', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'vacation-rentals');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'vacation-rentals' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'vacation-rentals', @top_ancestry, 3, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'vacation-rentals');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'TVRUNITS', 'tvrunits', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'TVRUNITS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'TVRUNITS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'TVRSHARE', 'tvrshare', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'TVRSHARE');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'TVRSHARE' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'subsidized-housing', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'subsidized-housing');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'subsidized-housing' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'subsidized-housing', @top_ancestry, 4, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'subsidized-housing');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'SUBSUNITS', 'subsunits', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'SUBSUNITS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'SUBSUNITS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'SUBSUNITSPERC', 'subsunitsperc', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'SUBSUNITSPERC');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'SUBSUNITSPERC' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');

-- Category: Property Market
INSERT INTO categories (universe, name, ancestry, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'property-market', @root_id, 3, 0, 0, 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'property-market');
SET @top_3_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'property-market' LIMIT 1);
SET @top_ancestry = CONCAT(@root_id, '/', @top_3_id);

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'homeownership', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'homeownership');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'homeownership' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'homeownership', @top_ancestry, 0, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'homeownership');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'OWNER', 'owner', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'OWNER');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'OWNER' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MORTGAGED', 'mortgaged', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MORTGAGED');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MORTGAGED' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'property-prices', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'property-prices');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'property-prices' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'property-prices', @top_ancestry, 1, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'property-prices');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDPRICETG_SFR', 'medpricetg_SFR', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_SFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_SFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDPRICETG_CND', 'medpricetg_CND', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_CND');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_CND' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDPRICETG_SFR_INDEX', 'medpricetg_SFR_index', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_SFR_INDEX');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_SFR_INDEX' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDPRICETG_CND_INDEX', 'medpricetg_CND_index', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_CND_INDEX');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDPRICETG_CND_INDEX' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'RSI', 'rsi', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'RSI');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'RSI' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 4, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'property-transactions', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'property-transactions');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'property-transactions' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'property-transactions', @top_ancestry, 2, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'property-transactions');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'TRANSACTIONS_SFR', 'transactions_SFR', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'TRANSACTIONS_SFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'TRANSACTIONS_SFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'INSTATE_SFR', 'instate_SFR', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'INSTATE_SFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'INSTATE_SFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'INSTATE_CND', 'instate_CND', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'INSTATE_CND');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'INSTATE_CND' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'OUTOFSTATE_SFR', 'outofstate_SFR', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'OUTOFSTATE_SFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'OUTOFSTATE_SFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'TRANSACTIONS_CND', 'transactions_CND', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'TRANSACTIONS_CND');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'TRANSACTIONS_CND' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 4, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'OUTOFSTATE_CND', 'outofstate_CND', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'OUTOFSTATE_CND');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'OUTOFSTATE_CND' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 5, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'home-affordability', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'home-affordability');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'home-affordability' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'home-affordability', @top_ancestry, 3, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'home-affordability');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDOWNERCOSTS', 'medownercosts', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDOWNERCOSTS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDOWNERCOSTS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDOWNERCOSTASPERINC', 'medownercostasperinc', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDOWNERCOSTASPERINC');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDOWNERCOSTASPERINC' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEEDEDINC_SFR', 'neededinc_sfr', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_SFR');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_SFR' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEEDEDINC_CND', 'neededinc_cnd', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_CND');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_CND' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');

-- Category: Rental Market
INSERT INTO categories (universe, name, ancestry, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'rental-market', @root_id, 4, 0, 0, 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'rental-market');
SET @top_4_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'rental-market' LIMIT 1);
SET @top_ancestry = CONCAT(@root_id, '/', @top_4_id);

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'rental-population', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'rental-population');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'rental-population' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'rental-population', @top_ancestry, 0, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'rental-population');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'RENTER', 'renter', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'RENTER');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'RENTER' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'rents', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'rents');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'rents' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'rents', @top_ancestry, 1, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'rents');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDRENT_ACS', 'medrent_acs', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDRENT_ACS');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDRENT_ACS' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDRENT_CRAIG', 'medrent_craig', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDRENT_CRAIG');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDRENT_CRAIG' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'rental-affordability', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'rental-affordability');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'rental-affordability' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'rental-affordability', @top_ancestry, 2, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'rental-affordability');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEEDEDINC_RENT_CRAIG', 'neededinc_rent_craig', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_RENT_CRAIG');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_RENT_CRAIG' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MEDRENTASPERINC', 'medrentasperinc', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDRENTASPERINC');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MEDRENTASPERINC' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'RENTBURD30', 'rentburd30', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'RENTBURD30');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'RENTBURD30' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'RENTBURD50', 'rentburd50', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'RENTBURD50');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'RENTBURD50' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 3, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'NEEDEDINC_RENT', 'neededinc_rent', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_RENT');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'NEEDEDINC_RENT' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 4, 'indent0');

-- Category: Zoning
INSERT INTO categories (universe, name, ancestry, list_order, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'zoning', @root_id, 5, 0, 0, 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'zoning');
SET @top_5_id = (SELECT CAST(id AS CHAR) FROM categories WHERE universe = 'HHF' AND ancestry = @root_id AND name = 'zoning' LIMIT 1);
SET @top_ancestry = CONCAT(@root_id, '/', @top_5_id);

INSERT INTO data_lists (universe, name, created_at, updated_at)
  SELECT 'HHF', 'zoning', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM data_lists WHERE universe = 'HHF' AND name = 'zoning');
SET @dl_id = (SELECT id FROM data_lists WHERE universe = 'HHF' AND name = 'zoning' LIMIT 1);
INSERT INTO categories (universe, name, ancestry, list_order, data_list_id, hidden, masked, header, created_at, updated_at)
  SELECT 'HHF', 'zoning', @top_ancestry, 0, @dl_id, 0, 0, 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM categories WHERE universe = 'HHF' AND ancestry = @top_ancestry AND name = 'zoning');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'ZONING', 'zoning', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'ZONING');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'ZONING' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 0, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'POPPERACRE', 'popperacre', 2, 0, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'POPPERACRE');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'POPPERACRE' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 1, 'indent0');
INSERT INTO measurements (universe, prefix, data_portal_name, decimals, `percent`, seasonal_adjustment, created_at, updated_at)
  SELECT 'HHF', 'MFR_SHARE', 'mfr_share', 1, 1, 'not_applicable', NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM measurements WHERE universe = 'HHF' AND prefix = 'MFR_SHARE');
SET @m_id = (SELECT id FROM measurements WHERE universe = 'HHF' AND prefix = 'MFR_SHARE' LIMIT 1);
INSERT IGNORE INTO data_list_measurements (data_list_id, measurement_id, list_order, indent) VALUES (@dl_id, @m_id, 2, 'indent0');

-- Geographies
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', 'HI', 'Hawaii', 'Hawaii', '15000', 'state', 0, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = 'HI');

INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', 'HAW', 'Hawaii County', 'HAW', '15001', 'county', 1, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = 'HAW');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', 'HON', 'Honolulu County', 'HON', '15003', 'county', 2, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = 'HON');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', 'KAU', 'Kauai County', 'KAU', '15007', 'county', 3, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = 'KAU');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', 'MAU', 'Maui County', 'MAU', '15009', 'county', 4, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = 'MAU');

INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96701', 'Waimalu, HI', '96701', '15003', 'zipcode', 100, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96701');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96703', 'Anahola, HI', '96703', '15007', 'zipcode', 101, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96703');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96704', 'Captain Cook, HI', '96704', '15001', 'zipcode', 102, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96704');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96705', 'Eleele, HI', '96705', '15007', 'zipcode', 103, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96705');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96706', 'Ewa Gentry, HI', '96706', '15003', 'zipcode', 104, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96706');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96707', 'Makakilo, HI', '96707', '15003', 'zipcode', 105, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96707');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96708', 'Haiku-Pauwela, HI', '96708', '15009', 'zipcode', 106, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96708');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96710', 'Hakalau, HI (PO Boxes)', '96710', '15001', 'zipcode', 107, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96710');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96712', 'Pupukea, HI', '96712', '15003', 'zipcode', 108, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96712');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96713', 'Hana, HI', '96713', '15009', 'zipcode', 109, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96713');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96714', 'Hanalei, HI', '96714', '15007', 'zipcode', 110, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96714');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96716', 'Hanapepe, HI', '96716', '15007', 'zipcode', 111, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96716');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96717', 'Hauula, HI', '96717', '15003', 'zipcode', 112, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96717');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96719', 'Hawi, HI', '96719', '15001', 'zipcode', 113, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96719');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96720', 'Hilo, HI', '96720', '15001', 'zipcode', 114, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96720');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96722', 'Princeville, HI', '96722', '15007', 'zipcode', 115, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96722');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96725', 'Honalo, HI', '96725', '15001', 'zipcode', 116, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96725');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96726', 'Honaunau-Napoopoo, HI', '96726', '15001', 'zipcode', 117, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96726');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96727', 'Honokaa, HI', '96727', '15001', 'zipcode', 118, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96727');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96728', 'Honomu, HI', '96728', '15001', 'zipcode', 119, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96728');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96729', 'Kualapuu, HI', '96729', '15009', 'zipcode', 120, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96729');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96730', 'Kaaawa, HI', '96730', '15003', 'zipcode', 121, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96730');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96731', 'Kahuku, HI', '96731', '15003', 'zipcode', 122, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96731');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96732', 'Kahului, HI', '96732', '15009', 'zipcode', 123, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96732');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96734', 'Kailua, HI', '96734', '15003', 'zipcode', 124, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96734');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96737', 'Hawaiian Ocean View, HI', '96737', '15001', 'zipcode', 125, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96737');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96738', 'Waikoloa Village, HI', '96738', '15001', 'zipcode', 126, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96738');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96740', 'Kailua, HI', '96740', '15001', 'zipcode', 127, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96740');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96741', 'Kalaheo, HI', '96741', '15007', 'zipcode', 128, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96741');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96743', 'Waimea, HI', '96743', '15001', 'zipcode', 129, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96743');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96744', 'Kaneohe, HI', '96744', '15003', 'zipcode', 130, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96744');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96746', 'Kapaa, HI', '96746', '15007', 'zipcode', 131, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96746');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96747', 'Kaumakani, HI', '96747', '15007', 'zipcode', 132, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96747');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96748', 'Kaunakakai, HI', '96748', '15009', 'zipcode', 133, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96748');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96749', 'Hawaiian Paradise Park, HI', '96749', '15001', 'zipcode', 134, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96749');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96750', 'Kealakekua, HI', '96750', '15001', 'zipcode', 135, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96750');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96751', 'Kealia, HI (PO Boxes)', '96751', '15007', 'zipcode', 136, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96751');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96752', 'Kekaha, HI', '96752', '15007', 'zipcode', 137, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96752');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96753', 'Kihei, HI', '96753', '15009', 'zipcode', 138, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96753');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96754', 'Kilauea, HI', '96754', '15007', 'zipcode', 139, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96754');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96755', 'Kapaau, HI', '96755', '15001', 'zipcode', 140, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96755');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96756', 'Koloa, HI', '96756', '15007', 'zipcode', 141, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96756');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96757', 'Kualapuu, HI', '96757', '15009', 'zipcode', 142, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96757');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96759', 'Kunia, HI (PO Boxes)', '96759', '15003', 'zipcode', 143, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96759');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96760', 'Hawaiian Acres, HI', '96760', '15001', 'zipcode', 144, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96760');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96761', 'Lahaina, HI', '96761', '15009', 'zipcode', 145, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96761');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96762', 'Laie, HI', '96762', '15003', 'zipcode', 146, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96762');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96763', 'Lanai City, HI', '96763', '15009', 'zipcode', 147, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96763');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96764', 'Laupahoehoe, HI', '96764', '15001', 'zipcode', 148, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96764');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96765', 'Lawai, HI', '96765', '15007', 'zipcode', 149, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96765');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96766', 'Lihue, HI', '96766', '15007', 'zipcode', 150, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96766');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96768', 'Pukalani, HI', '96768', '15009', 'zipcode', 151, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96768');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96769', 'Pakala Village, HI', '96769', '15007', 'zipcode', 152, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96769');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96770', 'Maunaloa, HI', '96770', '15009', 'zipcode', 153, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96770');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96771', 'Mountain View, HI', '96771', '15001', 'zipcode', 154, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96771');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96772', 'Discovery Harbour, HI', '96772', '15001', 'zipcode', 155, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96772');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96773', 'Ninole, HI (PO Boxes)', '96773', '15001', 'zipcode', 156, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96773');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96774', 'Ookala, HI (PO Boxes)', '96774', '15001', 'zipcode', 157, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96774');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96776', 'Paauilo, HI (PO Boxes)', '96776', '15001', 'zipcode', 158, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96776');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96777', 'Pahala, HI', '96777', '15001', 'zipcode', 159, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96777');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96778', 'Hawaiian Beaches, HI', '96778', '15001', 'zipcode', 160, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96778');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96779', 'Paia, HI', '96779', '15009', 'zipcode', 161, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96779');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96780', 'Papaaloa, HI (PO Boxes)', '96780', '15001', 'zipcode', 162, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96780');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96781', 'Papaikou, HI', '96781', '15001', 'zipcode', 163, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96781');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96782', 'Pearl City, HI', '96782', '15003', 'zipcode', 164, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96782');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96783', 'Pepeekeo, HI', '96783', '15001', 'zipcode', 165, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96783');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96785', 'Volcano, HI', '96785', '15001', 'zipcode', 166, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96785');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96786', 'Wahiawa, HI', '96786', '15003', 'zipcode', 167, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96786');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96789', 'Mililani Town, HI', '96789', '15003', 'zipcode', 168, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96789');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96790', 'Kula, HI', '96790', '15009', 'zipcode', 169, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96790');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96791', 'Waialua, HI', '96791', '15003', 'zipcode', 170, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96791');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96792', 'Waianae, HI', '96792', '15003', 'zipcode', 171, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96792');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96793', 'Wailuku, HI', '96793', '15009', 'zipcode', 172, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96793');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96795', 'Waimanalo, HI', '96795', '15003', 'zipcode', 173, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96795');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96796', 'Waimea, HI', '96796', '15007', 'zipcode', 174, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96796');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96797', 'Waipahu, HI', '96797', '15003', 'zipcode', 175, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96797');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96813', 'Urban Honolulu, HI', '96813', '15003', 'zipcode', 176, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96813');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96814', 'Urban Honolulu, HI', '96814', '15003', 'zipcode', 177, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96814');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96815', 'Urban Honolulu, HI', '96815', '15003', 'zipcode', 178, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96815');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96816', 'Urban Honolulu, HI', '96816', '15003', 'zipcode', 179, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96816');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96817', 'Urban Honolulu, HI', '96817', '15003', 'zipcode', 180, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96817');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96818', 'Urban Honolulu, HI', '96818', '15003', 'zipcode', 181, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96818');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96819', 'Urban Honolulu, HI', '96819', '15003', 'zipcode', 182, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96819');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96821', 'East Honolulu, HI', '96821', '15003', 'zipcode', 183, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96821');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96822', 'Urban Honolulu, HI', '96822', '15003', 'zipcode', 184, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96822');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96825', 'East Honolulu, HI', '96825', '15003', 'zipcode', 185, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96825');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96826', 'Urban Honolulu, HI', '96826', '15003', 'zipcode', 186, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96826');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96853', 'Hickam Housing, HI', '96853', '15003', 'zipcode', 187, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96853');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96857', 'Schofield Barracks, HI', '96857', '15003', 'zipcode', 188, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96857');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96859', 'Tripler Army Medical Center, HI', '96859', '15003', 'zipcode', 189, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96859');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96860', 'Pearl Harbor, HI', '96860', '15003', 'zipcode', 190, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96860');
INSERT INTO geographies (universe, handle, display_name, display_name_short, fips, geotype, list_order, created_at, updated_at)
  SELECT 'HHF', '96863', 'M C B H Kaneohe Bay, HI', '96863', '15003', 'zipcode', 191, NOW(), NOW()
  FROM dual WHERE NOT EXISTS (SELECT 1 FROM geographies WHERE universe = 'HHF' AND handle = '96863');
